submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 60
cpus_per_task: 20
tasks_per_node: 1
mem_gb: null
nodes: 1
name: ${hydra.job.name}
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
mem_per_gpu: null
mem_per_cpu: 5120
account: ls_krausea
additional_parameters: {"gpus": "rtx_2080_ti:1", "account": "ls_krausea"}
array_parallelism: 256
srun_args: ['--gpu-bind=single:1']